
TYPE
	GatherStateEnum : 
		(
		GATHER_IDLE,
		GATHER_SEG_AND_SEC,
		GATHER_SEG_AND_SEC_INFO,
		GATHER_DIVERTS,
		GATHER_SHUTTLE,
		GATHER_MOVE_TO_START,
		GATHER_MOVE_ALONG_SEC,
		GATHER_MONITOR_FOR_MIDPOINT,
		GATHER_ACKNOWLEDGE,
		GATHER_DONE
		);
END_TYPE
